name       : python-pexpect
version    : 4.8.0
release    : 14
source     :
    - https://github.com/pexpect/pexpect/archive/4.8.0.tar.gz : f2ea54a12cc893636a60421e8da0a36c40caad7825eb674697f1e25f5f91245e
homepage   : https://github.com/pexpect/pexpect
license    : ISC
component  : programming.python
summary    : Python module for spawning child applications
description: |
    Pexpect is a pure Python module for spawning child applications; controlling them; and responding to expected patterns in their output. Pexpect works like Don Libes' Expect. Pexpect allows your script to spawn a child application and control it as if a human were typing commands.
builddeps  :
    - man-db
    - ptyprocess
    - python-pytest
    - python2-pytest
rundeps    :
    - ptyprocess
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    # Woraround to fix failing tests: https://github.com/pexpect/pexpect/issues/669#issuecomment-758109973
    echo "set enable-bracketed-paste off" > .inputrc
    export INPUTRC=$PWD/.inputrc

    pushd $PKG_BUILD_DIR/py2build
        python ./tools/display-sighandlers.py
        python ./tools/display-terminalinfo.py
        py.test -v -k "not test_which_should_match_other_group_user"
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 ./tools/display-sighandlers.py
        python3 ./tools/display-terminalinfo.py
        py.test3 -v -k "not test_which_should_match_other_group_user"
    popd
