name       : python-pexpect
version    : 4.2.1
release    : 2
source     :
    - https://github.com/pexpect/pexpect/archive/4.2.1.tar.gz : f3e36792185a7b8b332a38846daa81d7e389688b7b63b9066d39c7f31a266a51
license    : ISC
component  : programming.python
summary    : Python module for spawning child applications
description: |
    Pexpect is a pure Python module for spawning child applications; controlling them; and responding to expected patterns in their output. Pexpect works like Don Libes' Expect. Pexpect allows your script to spawn a child application and control it as if a human were typing commands.
setup      : |
    %python_setup
install    : |
    %python_install 
